package top.niunaijun.blackbox.core.system.notification;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Context;
import android.graphics.Color;
import android.os.Build;

import androidx.annotation.RequiresApi;

import top.niunaijun.blackbox.BlackBoxCore;

/**
 * Manages the default notification channel used by the BlackBox host application itself.
 * <p>
 * On Android O (API 26) and above, this manager registers a high-importance notification
 * channel with red LED lights, badge support, and public lockscreen visibility. The
 * channel is used for notifications generated by the BlackBox container framework rather
 * than by virtual apps running inside it.
 * </p>
 */
public class NotificationChannelManager {
    private final static NotificationChannelManager sManager = new NotificationChannelManager();

    /** The default notification channel for the BlackBox host application. */
    public static NotificationChannel APP_CHANNEL;

    /**
     * Returns the singleton instance of the channel manager.
     *
     * @return the global {@link NotificationChannelManager} instance
     */
    public static NotificationChannelManager get() {
        return sManager;
    }

    /**
     * Constructs the channel manager and immediately registers the application notification
     * channel on Android O and above.
     */
    public NotificationChannelManager() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            registerAppChannel();
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.O)
    private void registerAppChannel() {
        NotificationManager nm = (NotificationManager) BlackBoxCore.getContext().getSystemService(Context.NOTIFICATION_SERVICE);
        String CHANNEL_ONE_ID = BlackBoxCore.getContext().getPackageName();
        String CHANNEL_ONE_NAME = "black-box-app";
        APP_CHANNEL = new NotificationChannel(CHANNEL_ONE_ID,
                CHANNEL_ONE_NAME, NotificationManager.IMPORTANCE_HIGH);
        APP_CHANNEL.enableLights(true);
        APP_CHANNEL.setLightColor(Color.RED);
        APP_CHANNEL.setShowBadge(true);
        APP_CHANNEL.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);
        nm.createNotificationChannel(APP_CHANNEL);
    }
}
